job_auditoria:
  runs-on: ubuntu-latest
  needs: job_gerador

  steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: meus-relatorios-oficiais
        path: artifacts

    - name: Listar arquivos baixados
      run: ls -R artifacts

    - name: Ler relatorio1
      run: cat artifacts/relatorio1.txt